import './globals.css'
import Header from '@/components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/> {/*header appear in every single page */}
        {children} {/* children is page content, EX: Home component in page.tsx  */}
      </body>
      
    </html>
  )
}
